using App.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace App.Infrastructure.Persistence.Configurations;

public class ContactConfiguration : IEntityTypeConfiguration<Contact>
{
    public void Configure(EntityTypeBuilder<Contact> builder)
    {
        // Manual ID generation - allows setting custom IDs for data migration
        // IDs are generated by INumericIdGenerator when not specified
        builder.Property(c => c.Id).ValueGeneratedNever();

        builder.HasKey(c => c.Id);

        builder.Property(c => c.Name).IsRequired().HasMaxLength(500);

        builder.Property(c => c.Email).HasMaxLength(500);

        builder.Property(c => c.OrganizationAccount).HasMaxLength(500);

        builder.HasOne(b => b.CreatorUser).WithMany().HasForeignKey(b => b.CreatorUserId);
        builder.HasOne(b => b.LastModifierUser).WithMany().HasForeignKey(b => b.LastModifierUserId);

        // Soft delete filter
        builder.HasQueryFilter(c => !c.IsDeleted);

        // Indexes
        builder.HasIndex(c => c.Email);
        builder.HasIndex(c => c.Name);
        builder.HasIndex(c => c.CreationTime);
    }
}
