using App.Application.Common.Interfaces;
using App.Application.Common.Models;
using App.Application.Common.Utils;
using App.Domain.Entities;
using CSharpVitamins;
using FluentValidation;
using Mediator;
using Microsoft.EntityFrameworkCore;

namespace App.Application.Admins.Commands;

public class CreateApiKey
{
    public record Command : LoggableRequest<CommandResponseDto<string>>
    {
        public ShortGuid UserId { get; init; }
    }

    public class Validator : AbstractValidator<Command>
    {
        public Validator(IAppDbContext db)
        {
            RuleFor(x => x)
                .CustomAsync(
                    async (request, context, cancellationToken) =>
                    {
                        var user = await db
                            .Users.AsNoTracking()
                            .FirstOrDefaultAsync(
                                p => p.Id == request.UserId.Guid,
                                cancellationToken
                            );

                        if (user == null || !user.IsAdmin)
                        {
                            context.AddFailure(
                                Constants.VALIDATION_SUMMARY,
                                "Must add the API key to an admin user."
                            );
                            return;
                        }

                        var numKeysAlready = await db
                            .ApiKeys.AsNoTracking()
                            .CountAsync(p => p.UserId == request.UserId.Guid, cancellationToken);
                        if (numKeysAlready >= 10)
                        {
                            context.AddFailure(
                                Constants.VALIDATION_SUMMARY,
                                "You have already hit your limit of 10 api keys per user."
                            );
                            return;
                        }
                    }
                );
        }
    }

    public class Handler : IRequestHandler<Command, CommandResponseDto<string>>
    {
        private readonly IAppDbContext _db;

        public Handler(IAppDbContext db)
        {
            _db = db;
        }

        public async ValueTask<CommandResponseDto<string>> Handle(
            Command request,
            CancellationToken cancellationToken
        )
        {
            var user = await _db.Users.FirstAsync(
                p => p.Id == request.UserId.Guid,
                cancellationToken
            );

            var autoGeneratedApiKey = Guid.NewGuid().ToString();

            var entity = new ApiKey
            {
                UserId = user.Id,
                ApiKeyHash = PasswordUtility.Hash(autoGeneratedApiKey),
            };

            _db.ApiKeys.Add(entity);

            await _db.SaveChangesAsync(cancellationToken);
            return new CommandResponseDto<string>(autoGeneratedApiKey);
        }
    }
}
